name: Deploy to Railway

on: workflow_dispatch
  push:
    branches: [ main ]   # mude se sua branch de produção for outra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token "$RAILWAY_TOKEN"
          railway whoami

      - name: Link project/service
        run: |
          railway link \
            --project "${{ secrets.PROJECT_ID }}" \
            --service "${{ secrets.SERVICE_ID }}"
          railway status

      - name: Deploy
        env:
          ENVIRONMENT_ID: ${{ secrets.ENVIRONMENT_ID }}
        run: |
          EXTRA=""
          if [ -n "$ENVIRONMENT_ID" ]; then
            EXTRA="--environment $ENVIRONMENT_ID"
          fi
          railway up --service "${{ secrets.SERVICE_ID }}" $EXTRA --detach
